// Generated by CoffeeScript 1.4.0

(function($) {
  "use strict";

  var App, initialize;
  App = {
    init: function() {
      console.log('Application has started');
      return this.appendP;
    },
    appendP: function() {
      console.log('appendP has run');
      $('.wrapper').append('<p>appendP function is running.</p>');
      return this.ajaxExample();
    },
    ajaxExample: function(callback) {
      return $.ajax({
        method: "POST",
        url: "#",
        data: {
          thing: 1,
          thing2: 2
        },
        success: function(data) {
          return callback(data);
        }
      });
    }
  };
  initialize = function() {
    return App.init();
  };
  return $(initialize);
})(jQuery);
